/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Adapter settings": {                            "en": "1MQTT instance settings",                          "de": "2MQTT Instanz-Einstellungen",
    "Always clean sessions for all clients": {       "en": "1Always clean sessions for all clients",           "de": "2Immer leere Session für alle Clients",
    "Always keep sessions for all clients": {        "en": "1Always keep sessions for all clients",            "de": "2Sessions für alle Clients behalten",
    "Authentication settings": {                     "en": "1Authentication settings",                         "de": "2Authentifizierungseinstellungen",
    "Chained certificate:": {                        "en": "1Chained certificate",                             "de": "2Verkettetes Zertifikat",
    "Client": {                                      "en": "1Client/subscriber",                               "de": "2Client/Subscriber",                                                                            
    "Client ID:": {                                  "en": "1Client ID",                                       "de": "2Client ID",                                                                                 
    "Connection": {                                  "en": "1Connection",                                      "de": "2Verbindung",                                                                                      
    "Connection settings": {                         "en": "1Connection settings",                             "de": "2Verbindungseinstellungen",                      ,            
    "Divided by comma": {                            "en": "1Divided by comma, e.g. 'mqtt/0/#,javascript/#'",  "de": "2Mit Komma getrennt, z.B 'mqtt/0/#,javascript/#'",
    "Enable first the adapter to test client.": {    "en": "1The instance needs to be enabled to be able to test the client.", "de": "2Die Instanz muss aktiviert sein um den Client zu testen.",
    "First save the adapter": {                      "en": "1The instance settings need to be saved first.",   "de": "2Die Instanz-Einstellungen müssen zuerst gespeichert werden.",               
    "Force clean session": {                         "en": "1Force clean session",                             "de": "2Leere Session erzwingen",                       
    "IP address": {                                  "en": "1IP address",                                      "de": "2IP Adresse",                                         
    "Interval before send topics by connection:": {  "en": "1Delay before sending topics to clients after connect", "de": "2Wartezeit vor dem Senden aller Topics bei neuen Verbindungen",
    "MQTT Settings": {                               "en": "1MQTT Settings",                                   "de": "2MQTT Einstellungen",                                                                      
    "MQTT adapter settings": {                       "en": "1MQTT instance settings",                          "de": "2MQTT Instanz-Einstellungen",                                                      
    "Main settings": {                               "en": "1General settings",                                "de": "2Allgemeine Einstellungen",                               
    "Mask to publish": {                             "en": "1e.g. 'mqtt.0.*,javascript.*'",                    "de": "2z.B. 'mqtt.0.*,javascript.*'",                  
    "Mask to publish own states:": {                 "en": "1Mask to publish own states",                      "de": "2Maske zum Bekanntgeben eigener States",                              
    "Max topic length:": {                           "en": "1Maximum topic name length",                       "de": "2Maximale Länge der Topic-Namen",                                             
    "Password confirmation:": {                      "en": "1Password confirmation",                           "de": "2Passwort-Wiederholung",                                                          
    "Password:": {                                   "en": "1Password",                                        "de": "2Kennwort",                                                                                          
    "Patterns:": {                                   "en": "1Subscribe patterns",                              "de": "2Subscribe Pattern",                                                               
    "Persistent Session": {                          "en": "1Persistent Session",                              "de": "2Dauerhafte Session",         
    "Port:": {                                       "en": "1Port",                                            "de": "2Port",                        
    "Prefix for topics:": {                          "en": "1Prefix for all topics",                           "de": "2Prefix für alle Topics",                                  
    "Private certificate:": {                        "en": "1Private certificate",                             "de": "2Privates Zertifikat",                                         
    "Public certificate:": {                         "en": "1Public certificate",                              "de": "2Öffentliches Zertifikat",                                                      
    "Publish all states at start:": {                "en": "1Publish own states on connect",                   "de": "2Eigene States beim Verbinden publizieren",         
    "Publish states on subscribe:": {                "en": "1Publish states on subscribe",                     "de": "2States bei subscribe publizieren",                   
    "Result: ": {                                    "en": "1Result: ",                                        "de": "2Ergebnis: ",                                                                                  
    "Secure:": {                                     "en": "1SSL",                                             "de": "2SSL",                                                                                               
    "Send interval:": {                              "en": "1Send delay",                                      "de": "2Sendeverzögerung",                                                                              
    "Send states (ack=true) too:": {                 "en": "1Send states (ack=true) too",                      "de": "2Sende auch Zustände (ack=true)",                      
    "Server": {                                      "en": "1Server/Broker",                                   "de": "2Server/Broker",                                                          
    "Set certificates or load it first in the system settings (right top).": {"en": "1Set certificates or define it first in the system settings (right top).", "de": "2Zertifikate wählen bzw. Zertifikate in den Systemeinstellungen (oben rechts) hinterlegen.", 
    "Store only on change:": {                       "en": "1Publish only on change",                          "de": "2Nur bei Änderungen publizieren",                             
    "Test connection": {                             "en": "1Test connection with Server",                     "de": "2Die Verbindung zum Server testen",                       
    "Trace output for every message:": {             "en": "1Trace output for every message",                  "de": "2Ausgabe jeder Nachricht loggen (debug)",        
    "Type:": {                                       "en": "1Type",                                            "de": "2Typ",                                                                                         
    "URL:": {                                        "en": "1URL",                                             "de": "2URL",                                                                                                 
    "Use WebSockets:": {                             "en": "1Use WebSockets",                                  "de": "2WebSockets benutzen",                                                                    
    "Use chunk patch:": {                            "en": "1Use chunk patch",                                 "de": "2Benutze Patch für Chunking",                                     
    "Use client settings": {                         "en": "1Use client settings",                             "de": "2Client-Einstellungen verwenden",
    "Use different topic names for set and get:": {  "en": "1Use different topic names for set and get",       "de": "2Unterschiedliche Topic-Namen für setzten und lesen nutzen",
    "User:": {                                       "en": "1User",                                            "de": "2Benutzer",
    "chars": {                                       "en": "1chars",                                           "de": "2Zeichen",
    "connected": {                                   "en": "1connected",                                       "de": "2verbunden",
    "ms": {                                          "en": "1ms",                                              "de": "2ms",
};
